const lang = {
    en : {
        Search : "Search",
        gptSerachPlaceholder : "What would you like to watch today?",
        Play : "Play",
        moreInfo : " More Info",
        nowPlaying : "Now Playing",
        topRated : "Top Rated",
        popular : "Popular",
        upcommingMovies : "Upcomming Movies",
        gptSearch : "GPT Search",
        home : "HomePage",
        signOut : "Sign Out",
        signIn : "Sign In",
        signUp : "Sign Up",
        fullName : "Full Name",
        emailAddress : "Email Address",
        password : "Password",
        signUptext : "Already registered? Sign In Now.",
        signIntext : "New to Netflix? Sign up now.",
        urlLang : "language=en",
    },
    hindi : {
        Search : "खोज",
        gptSerachPlaceholder : "आज आप क्या देखना चाहेंगे?",
        Play : "वीडियो चलाएं",
        moreInfo : "और जानकारी",
        nowPlaying : "अभी चल रहा है",
        topRated : "टॉप रेटेड",
        popular : "लोकप्रिय",
        upcommingMovies : "आने वाली फिल्में",
        gptSearch : "जीपीटी खोज",
        home : "होम पेज",
        signOut : "साइन आउट",
        signIn : "दाखिल करना",
        signUp : "साइन अप करें",
        fullName : "पूरा नाम",
        emailAddress : "मेल पता",
        password : "पासवर्ड",
        signUptext : "पहले से ही पंजीकृत? अब साइन इन करो।",
        signIntext : "नेटफ्लिक्स पर नए हैं? अभी साइनअप करें।",
        urlLang : "language=hi-IN",
    },
    spanish : {
        Search : "Buscar",
        gptSerachPlaceholder : "¿Qué te gustaría ver hoy?",
        Play : "reproduce el video",
        moreInfo : "Más información",
        nowPlaying : "Ahora reproduciendo vídeo",
        topRated : "Los más valorados",
        popular : "Popular",
        upcommingMovies : "Próximas películas",
        gptSearch : "Búsqueda GPT",
        home : "pagina de inicio",
        signOut : "Desconectar",
        signIn : "Iniciar sesión",
        signUp : "Inscribirse",
        fullName : "Nombre completo",
        emailAddress : "Dirección de correo electrónico",
        password : "Contraseña",
        signUptext : "¿Ya registrado? Regístrate.",
        signIntext : "¿Nuevo en Netflix? Regístrate ahora.",
        urlLang : "language=es-ES",
    },
}

export default lang;